# MySQL 설정

#createDatabaseIfNotExist: 데이터베이스가 존재하지 않으면 자동으로 생성
#useUnicode: 유니코드 사용 여부 설정
#characterEncoding: 문자열 인코딩 종류 설정
#characterSetResult: 결과값의 인코딩 종류 설정
#useSSL: SSL 사용여부 설정

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eat_together?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: eattogether
    password: 1234
  jpa:
    show-sql: true
    hibernate: ddl-auto=update
    properties:
      hibernate:
        format_sql: true